# Generated by Django 5.0.6 on 2024-05-09 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('middle_name', models.CharField(max_length=50, verbose_name='По-Батькові')),
                ('phone', models.CharField(max_length=15, verbose_name='Номер телефону')),
                ('email', models.EmailField(max_length=30, verbose_name='Електронна адреса')),
                ('specialization', models.CharField(choices=[('ther', 'Терапевтична стоматологія'), ('orth', 'Ортодонтія'), ('oral', 'Хірургічна стоматологія'), ('endo', 'Ендодонтія'), ('peri', 'Періодонтологія'), ('pedi', 'Педіатрична стоматологія'), ('pros', 'Протезування')], max_length=4, verbose_name='Спеціалізація')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото лікаря')),
            ],
            options={
                'ordering': ['specialization'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('phone', models.CharField(max_length=15, verbose_name='Номер телефону')),
                ('email', models.EmailField(max_length=30, verbose_name='Електронна адреса')),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Назва процедури')),
                ('price', models.IntegerField(verbose_name='Ціна процедури')),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Дата та час проведення процедури')),
                ('status', models.CharField(blank=True, choices=[('p', 'Заплановано'), ('c', 'Підтверджено'), ('d', 'Виконано'), ('o', 'Прострочено')], default='p', max_length=1, verbose_name='Статус процедури')),
                ('details', models.TextField(blank=True, max_length=200, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.doctor', verbose_name='Лікар')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.patient', verbose_name='Пацієнт')),
                ('procedure_type', models.ManyToManyField(to='index.proceduretype', verbose_name='Назва процедури')),
            ],
            options={
                'ordering': ['date_time'],
            },
        ),
    ]
