# Generated by Django 5.0.6 on 2024-05-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceduretype',
            name='details',
            field=models.TextField(default=1, max_length=200, verbose_name='Деталі'),
            preserve_default=False,
        ),
    ]
