# Generated by Django 5.0.6 on 2024-05-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_proceduretype_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceduretype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва процедури'),
        ),
    ]
