# Generated by Django 5.0.6 on 2024-05-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_proceduretype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='details',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Деталі'),
        ),
    ]
