# Generated by Django 5.0.6 on 2024-05-09 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_procedure_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(upload_to='images/', verbose_name='Фото лікаря'),
        ),
    ]
