# Generated by Django 5.0.6 on 2024-05-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_alter_procedure_patient_delete_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='status',
            field=models.CharField(choices=[('p', 'Заплановано'), ('c', 'Підтверджено'), ('d', 'Виконано'), ('o', 'Прострочено')], default='p', max_length=1, verbose_name='Статус процедури'),
        ),
    ]
