# Generated by Django 5.0.6 on 2024-05-14 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_alter_doctor_options_alter_procedure_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['specialization']},
        ),
        migrations.AlterModelOptions(
            name='procedure',
            options={'ordering': ['date_time']},
        ),
    ]
