# Generated by Django 5.0.6 on 2024-05-14 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_alter_doctor_options_alter_procedure_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['specialization'], 'permissions': (('can_edit_doctor', 'Може редагувати лікарів'), ('can_delete_doctor', 'Може видаляти лікарів'), ('can_add_doctor', 'Може додавати лікарів'))},
        ),
        migrations.AlterModelOptions(
            name='procedure',
            options={'ordering': ['date_time'], 'permissions': (('can_edit_procedure', 'Може редагувати процедури'), ('can_add_procedure', 'Може додавати процедури'), ('can_set_procedure', 'Може переглядати процедури'))},
        ),
    ]
