# Generated by Django 5.0.6 on 2024-05-21 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_alter_doctor_options_alter_procedure_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proceduretype',
            options={'ordering': ['name'], 'permissions': (('can_edit_procedure_type', 'Може редагувати послуги'), ('can_add_procedure_type', 'Може додавати послуги'), ('can_set_procedure_type', 'Може переглядати послуги'))},
        ),
    ]
