# Generated by Django 5.0.6 on 2024-05-21 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_alter_proceduretype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedure',
            options={'ordering': ['date_time'], 'permissions': (('can_edit_procedure', 'Може редагувати процедури'), ('can_add_procedure', 'Може додавати процедури'), ('can_delete_procedure', 'Може видаляти процедури'))},
        ),
        migrations.AlterModelOptions(
            name='proceduretype',
            options={'ordering': ['name'], 'permissions': (('can_edit_procedure_type', 'Може редагувати послуги'), ('can_add_procedure_type', 'Може додавати послуги'), ('can_delete_procedure_type', 'Може видаляти послуги'))},
        ),
    ]
